on:
  push:
    branches:
    - master

jobs:
  build-and-push-image:
    name: build and push image to container registry
    runs-on: ubuntu-22.04
    steps:
      - name: check list file
        run: ls -la
      - name: clone repository
        uses: actions/checkout@v4
      - name: check list file
        run: ls -la
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: adhithia21/golangapp:${{ github.run_number }}

  deploy:
    name: deploy container to server
    runs-on: ubuntu-22.04
    needs:
    - build-and-push-image
    steps:
      - name: test
        run: echo "test workflow"
      - name: deploy to server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: 152.42.176.84
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: whoami